name: commands workflow
on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true
          if [[ depricated ]];
          then
            echo "::warning:: running a derpicated function"
          fi
      - name: set api name
        run: echo "API_NAME=my-api" >> $GITHUB_ENV
      - name: log api name
        run: |
          echo "::addmask::$API_NAME"
          echo "$API_NAME"
