name: first-workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.4.0
      - name: Install apache2
        run: apt install apache2 -y
      - name: Add our webpage to the server
        run: cp index.html /var/www/html
      - name: Start webserver
        run: systemctl enable --now apache2
      - name: Run testing bash script
        run: sh test.sh
