name: first-workflow # workflow name

on:                  # trigger workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:                # jobs to run
  checkout:          # job name
    runs-on: ubuntu-latest      # runner environment
    steps:                      # steps to run in the job
      - name: checkout code
        uses: actions/checkout@v6.1.0
      - name: list repository files
        run: ls -la
  test:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: log action
        run: echo "Push or pull request event triggered"
