name: push-pr.yml
on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: log action
        run: echo "Push or pull request event triggered on python files"
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.1.0
      - name: list repository files
        run: pwd; ls -la 
  test:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: run main code
        run: python3 ./src/main.py
      - name: run code tests
        run: bash ./src/test.sh