on:
    workflow_dispatch:
    #schedule:
      #  - cron: '*/5 * * * *' # run every 5 minutes
jobs:
    log:
        runs-on: ubuntu-latest
        steps:
        - name: log action
          run: echo "Running scheduled workflow"
